src/Entity/Calendar.php
<?php

namespace App\Entity;

use App\Repository\CalendarRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CalendarRepository::class)]
class Calendar
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $title;

    #[ORM\Column(type: 'datetime')]
    private $start;

    #[ORM\Column(type: 'datetime')]
    private $end;

    #[ORM\Column(type: 'text')]
    private $description;

    #[ORM\Column(type: 'boolean')]
    private $all_day;

    #[ORM\Column(type: 'string', length: 7)]
    private $background_color;

    #[ORM\Column(type: 'string', length: 7)]
    private $border_color;

    #[ORM\Column(type: 'string', length: 7)]
    private $text_color;

    #[ORM\Column(type: 'string', length: 255)]
    private $active;

    // #[ORM\ManyToOne(targetEntity: Dossier::class, inversedBy: 'calendars')]
    // private $dossier;

 
    #[ORM\ManyToOne(inversedBy: 'calendars')]
    private ?Entreprise $entreprise = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getStart(): ?\DateTimeInterface
    {
        return $this->start;
    }

    public function setStart(\DateTimeInterface $start): self
    {
        $this->start = $start;

        return $this;
    }

    public function getEnd(): ?\DateTimeInterface
    {
        return $this->end;
    }

    public function setEnd(\DateTimeInterface $end): self
    {
        $this->end = $end;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getAllDay(): ?bool
    {
        return $this->all_day;
    }

    public function setAllDay(bool $all_day): self
    {
        $this->all_day = $all_day;

        return $this;
    }

    public function getBackgroundColor(): ?string
    {
        return $this->background_color;
    }

    public function setBackgroundColor(string $background_color): self
    {
        $this->background_color = $background_color;

        return $this;
    }

    public function getBorderColor(): ?string
    {
        return $this->border_color;
    }

    public function setBorderColor(string $border_color): self
    {
        $this->border_color = $border_color;

        return $this;
    }

    public function getTextColor(): ?string
    {
        return $this->text_color;
    }

    public function setTextColor(string $text_color): self
    {
        $this->text_color = $text_color;

        return $this;
    }

    public function getActive(): ?string
    {
        return $this->active;
    }

    public function setActive(string $active): self
    {
        $this->active = $active;

        return $this;
    }

    // public function getDossier(): ?Dossier
    // {
    //     return $this->dossier;
    // }

    // public function setDossier(?Dossier $dossier): self
    // {
    //     $this->dossier = $dossier;

    //     return $this;
    // }

    // public function getEntreprise(): ?Entreprise
    // {
    //     return $this->entreprise;
    // }

    // public function setEntreprise(?Entreprise $entreprise): static
    // {
    //     $this->entreprise = $entreprise;

    //     return $this;
    // }

  
}

src/Form/CalendarType.php
<?php

namespace App\Form;

use App\Entity\Calendar;
use App\Entity\Client;
use App\Entity\Dossier;
use App\Entity\User;
use Doctrine\ORM\EntityRepository;
use Mpdf\Tag\TextArea;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ColorType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\GreaterThan;
use Symfony\Component\Validator\Constraints\NotBlank;

class CalendarType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            // ->add('dossier', EntityType::class, [
            //     'required' => false,
            //     'class' => Dossier::class,
            //     'query_builder' => function (EntityRepository $er) {
            //         return $er->createQueryBuilder('u')
            //             // ->where('u.active = :val')
            //             // ->setParameter('val', 1)
            //             ->orderBy('u.id', 'DESC');
            //     },
            //     'label' => 'Acte conserné',
            //     'placeholder' => "Selectionner l'acte",
            //     'choice_label' => function ($dossier) {
                 
            //             return 'Dossier N°' . $dossier->getNumeroOuverture() ;
            //     },
            //     'attr' => ['class' => 'form-control has-select2', 'id' => 'validationCustom05']

            // ])
            ->add('start', DateTimeType::class, [
                "required" => false,
                "widget" => 'single_text',
                "input_format" => 'Y-m-d',
                "by_reference" => true,
                "empty_data" => new \DateTime(),
                'attr' => ['class' => 'start'],
                'constraints' => [
                    new NotBlank([
                        'message' => 'La date de début ne doit pas être vide vous de devez renseigner les heures aussi'
                    ]),
                ]
            ])
            ->add('end', DateTimeType::class, [
                "required" => false,
                "widget" => 'single_text',
                "input_format" => 'Y-m-d',
                "by_reference" => true,
                "empty_data" => '',
                'attr' => ['class' => 'dateFin'],
                'constraints' => [
                    new NotBlank(
                        [
                            'message' => 'La date de fin ne doit pas être vide vous de devez renseigner les heures aussi'
                        ]
                    ),

                    new GreaterThan([
                        'propertyPath' => 'parent.all[start].data',
                        'message' => 'La date de fin ne doit pas être inférieure à la date de début',
                    ]),
                ]
            ])
            ->add('description', TextareaType::class);
        /* ->add('all_day', CheckboxType::class, [
                'label' => false,
                'required' => false,
            ])
            ->add('background_color', ColorType::class)
            ->add('border_color', ColorType::class)
            ->add('text_color', ColorType::class);*/
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Calendar::class,
        ]);
    }
}

src/Controller/Agenda/CalendarController.php
<?php

namespace App\Controller\Agenda;

use App\Entity\Calendar;
use App\Form\Calendar1Type;
use App\Repository\CalendarRepository;
use App\Service\ActionRender;
use App\Service\FormError;
use Omines\DataTablesBundle\Adapter\Doctrine\ORMAdapter;
use Omines\DataTablesBundle\Column\BoolColumn;
use Omines\DataTablesBundle\Column\DateTimeColumn;
use Omines\DataTablesBundle\Column\TextColumn;
use Omines\DataTablesBundle\DataTableFactory;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;
use App\Controller\BaseController;
use App\Form\CalendarType;
use Doctrine\ORM\QueryBuilder;

#[Route('/ads/agenda/calendar')]
class CalendarController extends BaseController
{
    const INDEX_ROOT_NAME = 'app_agenda_calendar_index';

    #[Route('/{etat}', name: 'app_agenda_calendar_index', methods: ['GET', 'POST'])]
    public function index(Request $request, DataTableFactory $dataTableFactory, $etat): Response
    {


        $permission = $this->menu->getPermissionIfDifferentNull($this->security->getUser()->getGroupe()->getId(), self::INDEX_ROOT_NAME);

        $table = $dataTableFactory->create()
            ->add('title', TextColumn::class, ['label' => 'Titre'])
            ->add('start', DateTimeColumn::class,  ['label' => 'Date début', 'format' => 'd/m/Y', 'searchable' => false])
            ->add('end', DateTimeColumn::class, ['label' => 'Date fin', 'format' => 'd/m/Y', 'searchable' => false])

            ->createAdapter(ORMAdapter::class, [
                'entity' => Calendar::class,
                'query' => function (QueryBuilder $qb) use ($etat) {
                    $qb->select(['p',])
                        ->from(Calendar::class, 'p')
                        // ->join('p.entreprise', 'en')
                        ->orderBy('p.id ', 'DESC');
                    // if ($this->groupe != "SADM") {
                    //     $qb->andWhere('en = :entreprise')
                    //         ->setParameter('entreprise', $this->entreprise);
                    // }
                    if ($etat == "passe") {
                        $qb->andWhere('p.start <= :start or p.end <= :start')
                            ->setParameter('start', new \DateTime());
                    } elseif ($etat == "prochain") {
                        $qb->andWhere('p.end > :end')
                            ->setParameter('end', new \DateTime());
                    }
                }
            ])
            ->setName('dt_app_agenda_calendar' . $etat);
        if ($permission != null) {

            $renders = [
                'edit' => new ActionRender(function () use ($permission) {
                    if ($permission == 'R') {
                        return false;
                    } elseif ($permission == 'RD') {
                        return false;
                    } elseif ($permission == 'RU') {
                        return true;
                    } elseif ($permission == 'CRUD') {
                        return true;
                    } elseif ($permission == 'CRU') {
                        return true;
                    } elseif ($permission == 'CR') {
                        return false;
                    }
                }),
                'delete' => new ActionRender(function () use ($permission) {
                    if ($permission == 'R') {
                        return false;
                    } elseif ($permission == 'RD') {
                        return true;
                    } elseif ($permission == 'RU') {
                        return false;
                    } elseif ($permission == 'CRUD') {
                        return true;
                    } elseif ($permission == 'CRU') {
                        return false;
                    } elseif ($permission == 'CR') {
                        return false;
                    }
                }),
                'show' => new ActionRender(function () use ($permission) {
                    if ($permission == 'R') {
                        return true;
                    } elseif ($permission == 'RD') {
                        return true;
                    } elseif ($permission == 'RU') {
                        return true;
                    } elseif ($permission == 'CRUD') {
                        return true;
                    } elseif ($permission == 'CRU') {
                        return true;
                    } elseif ($permission == 'CR') {
                        return true;
                    }
                }),

            ];


            $hasActions = false;

            foreach ($renders as $_ => $cb) {
                if ($cb->execute()) {
                    $hasActions = true;
                    break;
                }
            }

            if ($hasActions) {
                $table->add('id', TextColumn::class, [
                    'label' => 'Actions',
                    'orderable' => false,
                    'globalSearchable' => false,
                    'className' => 'grid_row_actions',
                    'render' => function ($value, Calendar $context) use ($renders) {
                        $options = [
                            'default_class' => 'btn btn-xs btn-clean btn-icon mr-2 ',
                            'target' => '#exampleModalSizeLg2',


                            'actions' => [
                                'edit' => [
                                    'target' => '#exampleModalSizeSm2',
                                    'url' => $this->generateUrl('app_agenda_calendar_edit', ['id' => $value]),
                                    'ajax' => true,
                                    'icon' => '%icon% bi bi-pen',
                                    'attrs' => ['class' => 'btn-default'],
                                    'render' => $renders['edit']
                                ],
                                'show' => [
                                    'url' => $this->generateUrl('app_agenda_calendar_show', ['id' => $value]),
                                    'ajax' => true,
                                    'icon' => '%icon% bi bi-eye',
                                    'attrs' => ['class' => 'btn-primary'],
                                    'render' => $renders['show']
                                ],
                                'delete' => [
                                    'target' => '#exampleModalSizeNormal',
                                    'url' => $this->generateUrl('app_agenda_calendar_delete', ['id' => $value]),
                                    'ajax' => true,
                                    'icon' => '%icon% bi bi-trash',
                                    'attrs' => ['class' => 'btn-main'],
                                    'render' => $renders['delete']
                                ]
                            ]

                        ];
                        return $this->renderView('_includes/default_actions.html.twig', compact('options', 'context'));
                    }
                ]);
            }
        }

        $table->handleRequest($request);

        if ($table->isCallback()) {
            return $table->getResponse();
        }


        return $this->render('agenda/calendar/index.html.twig', [
            'datatable' => $table,
            'permition' => $permission,
            'etat' => $etat,
            'titre' => "Liste des  activités"
        ]);
    }

    #[Route('/new/new', name: 'app_agenda_calendar_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, FormError $formError): Response
    {

        $titre = "Ajouter un événement";
        $calendar = new Calendar();
        $form = $this->createForm(CalendarType::class, $calendar, [
            'method' => 'POST',
            'action' => $this->generateUrl('app_agenda_calendar_new')
        ]);
        $form->handleRequest($request);

        $data = null;
        $statutCode = Response::HTTP_OK;

        $isAjax = $request->isXmlHttpRequest();
        // dd($form->getData());
        if ($form->isSubmitted()) {

            $response = [];
            $redirect = $this->generateUrl('app_config_parametre_agenda_index');
            //$email = "";
            // if ($form->getData()->getClient()->getRaisonSocial() == "") {
            //     $email = $form->getData()->getClient()->getEmail();
            // } else {

            //     $email = $form->getData()->getClient()->getEmailEntreprise();
            // }

            // $identite = "";
            // //dd($form->getData()->getClient());
            // if ($form->getData()->getClient()->getRaisonSocial() == "") {
            //     $identite = $form->getData()->getClient()->getNom() . " " . $form->getData()->getClient()->getPrenom();
            // } else {

            //     $identite = $form->getData()->getClient()->getRaisonSocial();
            // }

            //$objet = $form->getData()->getDescription();
            if ($form->isValid()) {
                /*     $mailerService->send(
                    'INFORMATION CONCERNANT LE RENDEZ-VOUS',
                    'konatenvaly@gmail.com',
                    $email,
                    "_admin/contact/template.html.twig",
                    [
                        'message' =>  $objet,
                        'entreprise' =>  "Notari",
                        'identite' =>  $identite,
                        'telephone' =>  '0704314164'
                    ]
                );*/
                $calendar->setActive(1)
                    ->setAllDay(false)
                    ->setBackgroundColor("#31F74F")
                    ->setBorderColor("#BBF0DA")
                    ->setTextColor("#FAF421");

templates/agenda/calendar/delete.html.twig
{% block page_content %}
    {% form_theme form 'widget/fields-block.html.twig' %}
    <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Suppression</h5>
        <div class="btn btn-icon btn-sm  ms-2" data-bs-dismiss="modal" aria-label="Close">
            <span class="svg-icon svg-icon-2x text-white">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
					<rect opacity="0.5" x="6" y="17.3137" width="16" height="2" rx="1" transform="rotate(-45 6 17.3137)" fill="currentColor"></rect>
					<rect x="7.41422" y="6" width="16" height="2" rx="1" transform="rotate(45 7.41422 6)" fill="currentColor"></rect>
				</svg>
            </span>
        </div>
    </div>
    {{ form_start(form, {'attr': {'class':'form-horizontal', 'role':'form'}}) }}
        <div class="modal-body">
             {{ include('_includes/ajax/response.html.twig') }}
             <div class="alert alert-custom alert-outline-danger fade show mb-5" role="alert">
                <div class="alert-icon"><i class="flaticon-warning"></i></div>
                <div class="alert-text">Voulez-vous vraiment supprimer cet enregistrement?</div>
            </div>
            {{ form_widget(form) }}
        </div>
        <div class="modal-footer">
            <button type="button" class="btn  btn-default btn-sm" data-bs-dismiss="modal">Fermer</button>
            <button type="submit" class="btn btn-main btn-ajax btn-sm"><span class="spinner-border d-none  spinner-ajax spinner-border-sm" role="status" aria-hidden="true"></span> Supprimer</button>
        </div>
    {{ form_end(form) }}
{% endblock %}

{% block java %}
    <script>
    </script>
{% endblock %}

templates/agenda/calendar/edit.html.twig
{% block page_content %}
    {% form_theme form 'widget/fields-block.html.twig' %}
    <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Edition de l'activité</h5>
        <div class="btn btn-icon btn-sm  ms-2" data-bs-dismiss="modal" aria-label="Close">
            <span class="svg-icon svg-icon-2x text-white">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
					<rect opacity="0.5" x="6" y="17.3137" width="16" height="2" rx="1" transform="rotate(-45 6 17.3137)" fill="currentColor"></rect>
					<rect x="7.41422" y="6" width="16" height="2" rx="1" transform="rotate(45 7.41422 6)" fill="currentColor"></rect>
				</svg>
            </span>
        </div>
    </div>
    {{ form_start(form, {'attr': {'role':'form', 'class': 'form'}}) }}
    <div class="modal-body content-doc">
        {{ include('_includes/ajax/response.html.twig') }}
        <div class="contenu" style="margin-top: -10px">
            <div class="row">
                <div class="form-group col-md-6 ">
                    <label class="sr-onl" for="userinput1">Titre</label>
                    {{ form_widget(form.title) }}
                    {# <input type="text" id="userinput1" class="form-control border-primary" placeholder="Compte contribuable" name="name">#}
                </div>
                {# <div class="form-group col-md-6">
                    <label class="sr-onl" for="userinput1">Client</label>
                    {{ form_widget(form.dossier) }}
                    {# <input type="text" id="userinput1" class="form-control border-primary" placeholder="Compte contribuable" name="name">
                </div> #}
            </div>
            <div class="row">
                <div class="form-group col-md-12">
                    <label class="sr-onl" for="userinput1">Description</label>
                    {{ form_widget(form.description) }}
                    {# <input type="text" id="userinput1" class="form-control border-primary" placeholder="Compte contribuable" name="name">#}
                </div>

            </div>
            <div class="row">
                <div class="form-group col-md-6 ">
                    <label class="sr-onl" for="userinput1">Debut</label>
                    {{ form_widget(form.start) }}

                </div>
                <div class="form-group col-md-6 ">
                    <label class="sr-onl" for="userinput1">Fin</label>
                    {{ form_widget(form.end) }}
                    {# <input type="text" id="userinput1" class="form-control border-primary" placeholder="Compte contribuable" name="name">#}
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" id="sendByEmail">
                        <label class="form-check-label" for="sendByEmail">
                            Envoyer par mail
                        </label>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <div class="modal-footer">
        {# {{ include('_includes/ajax/loader.html.twig') }} #}
        <button type="button" class="btn btn-default btn-sm" data-bs-dismiss="modal">Annuler</button>
        <button type="submit" class="btn btn-main btn-ajax btn-sm"><span class="spinner-border d-none  spinner-ajax spinner-border-sm" role="status" aria-hidden="true"></span> Valider</button>
    </div>
    {{ form_end(form) }}
{% endblock %}

{% block java %}
    <script>
        $(function () {
            init_select2('select');
        });
        $(function () {
            init_select2('select', null, '.content-doc');
        });
          $(function () {
            $('.no-auto').each(function () {
                const $this = $(this);
                const $id = $('#' + $this.attr('id'));
                init_date_picker($id,  'down', (start, e) => {
                    //$this.val(start.format('DD/MM/YYYY'));
                }, null, null, false);

                $id.on('apply.daterangepicker', function (ev, picker) {
                    $(this).val(picker.startDate.format('DD/MM/YYYY'));
                });
            });
        });
    </script>
{% endblock %}

templates/agenda/calendar/index.html.twig
{# {% extends 'base-layout.html.twig' %}

{% block title %}Liste des calendars{% endblock %}
{% block header %}calendars{% endblock %}
{% block breadcrumb %}{% endblock %} #}
{% block body %}
<div class="card shadow-sm">
    <div class="card-header card-header-sm">
        <h3 class="card-title"> Liste des activités</h3>
        <div class="card-toolbar">
            {% if permition in ["CR","CRU","CRUD"] %}
           {#  <a href="{{ path('app_agenda_calendar_new') }}" class="btn btn-main btn-sm"  
                data-bs-toggle="modal" data-bs-target="#exampleModalSizeLg2">
                <i class="bi bi-plus-square text-light"></i>
                Nouveau
            </a> #}
            {% endif %}
        </div>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-sm-12">
                {% if permition != null %}
                <div id="grid_app_agenda_calendar" class="grid-dt-wrapper">Chargement....</div>
                {% else %}
                <div class="d-flex flex-column flex-center flex-column-fluid">
                    <!--begin::Content-->
                    <div class="d-flex flex-column flex-center text-center ">
                        <!--begin::Wrapper-->
                        <div class="card card-flush w-lg-650px py-5">
                            <div class="card-body py-1 py-lg-20" style="margin-top: -88px">

                                <!--begin::Title-->
                                 {% include "_includes/message_error.html.twig" %}
                                <!--end::Title-->
                                <!--begin::Illustration-->
                               


                            </div>
                        </div>
                        <!--end::Wrapper-->
                    </div>
                    <!--end::Content-->
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}


{% block java %}
    <script src="{{ asset('assets/js/datatables.js') }}"></script>
    <script> 
        $(function() { 
              $('#grid_app_agenda_calendar').initDataTables({{ datatable_settings(datatable) }}, {
                  searching: true,
                  ajaxUrl: "{{ path('app_agenda_calendar_index',{'etat':etat}) }}",
                  language: {
                      url: asset_base_path + "/js/i18n/French.json"
                  }
              });
        });
    </script>
{% endblock %}

templates/agenda/calendar/show.html.twig
{% block page_content %}
<div class="modal-header">
    <h4 class="modal-title">Détails sur une activité</h4>
    <div class="btn btn-icon btn-sm  ms-2" data-bs-dismiss="modal" aria-label="Close">
        <span class="svg-icon svg-icon-2x text-white">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <rect opacity="0.5" x="6" y="17.3137" width="16" height="2" rx="1" transform="rotate(-45 6 17.3137)"
                    fill="currentColor"></rect>
                <rect x="7.41422" y="6" width="16" height="2" rx="1" transform="rotate(45 7.41422 6)"
                    fill="currentColor"></rect>
            </svg>
        </span>
    </div>
</div>

<div class="modal-body">
    <table class="table table-bordered">
        <tbody>
            {# <tr class="fw-bold">#}
                {#<th>Id</th>#}
                {#<td>{{ calendar.id }}</td>#}
            </tr>
            <tr class="fw-bold">
                <th>Title</th>
                <td>{{ calendar.title }}</td>
            </tr>
            <tr class="fw-bold">
                <th>Start</th>
                <td>{{ calendar.start ? calendar.start|date('d/m/Y') ~ ' à ' ~ calendar.start|date('H:i') : '' }}</td>


            </tr>
            <tr class="fw-bold">
                <th>End</th>
                <td>{{ calendar.end ? calendar.end|date('d/m/Y') ~ ' à ' ~ calendar.end|date('H:i') }}</td>



            </tr>
            <tr class="fw-bold">
                <th>Description</th>
                <td>{{ calendar.description }}</td>
            </tr>

            {# <tr>#}
                {# <th>All_day</th>#}
                {# <td>{{ calendar.allDay ? 'Yes' : 'No' }}</td>#}
                {#</tr>#}
            {# <tr>#}
                {# <th>Background_color</th>#}
                {# <td>{{ calendar.backgroundColor }}</td>#}
                {#</tr>#}
            {# <tr>#}
                {# <th>Border_color</th>#}
                {# <td>{{ calendar.borderColor }}</td>#}
                {#</tr>#}
            {# <tr>#}
                {# <th>Text_color</th>#}
                {# <td>{{ calendar.textColor }}</td>#}
                {#</tr>#}
            {# <tr>#}
                {# <th>Active</th>#}
                {# <td>{{ calendar.active }}</td>#}
                {#</tr>#}
        </tbody>
    </table>
</div>
<div class="modal-footer">
    <button type="button" class="btn dark btn-outline" data-bs-dismiss="modal">Fermer</button>
</div>

{% endblock %}
{% block java %}
<script>

</script>
{% endblock %}